#adi= input("Adınız Nedir?")
#print("Merhaba", adi)
#print("""Ankara'ya öyle yakışırdı ki kar""")
#print("Merhaba")
#print('Merhaba')
#print("Hulk","Ironman","Thor","Captain America", sep="\n")
print("""{} Universitesi {} Bölümü""".format("Bilkent", "Malzeme Bilimi ve Nanoteknoloji"))
print("Hulk","Ironman","Thor","Captain America", sep=".")
#print("Hulk","Ironman","Thor","Captain America", end="\n")